name: Java CI Build with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 17
            additional-maven-args: "-Pjacoco,mutation-testing,docker"
          - java: 21

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: xvfb-run mvn clean verify ${{ matrix.additional-maven-args }}
        working-directory: ./sessionBuilder
        env:
          POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
          POSTGRES_TEST_USER: ${{ secrets.POSTGRES_TEST_USER }}
          POSTGRES_TEST_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}

      - name: Build Docker Image
        if: matrix.java == '17'
        run: mvn clean package -Pdocker
        working-directory: ./sessionBuilder-app

      - name: Login to DockerHub
        if: matrix.java == '17' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        if: matrix.java == '17' && github.ref == 'refs/heads/main'
        run: |
          docker tag sessionbuilder-app:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/sessionbuilder-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sessionbuilder-app:latest
        working-directory: ./sessionBuilder-app

      - name: Upload to Coveralls (non blocking)
        if: matrix.java == '17'
        run: mvn coveralls:report || echo "Coveralls failed but build continues"
        working-directory: ./sessionBuilder
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}

      - name: Archive Surefire XML reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-xml-jdk-${{ matrix.java }}
          path: '**/target/surefire-reports/'