name: Java CI Build with Maven

on:
  push:
  pull_request:

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLOUD }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 17
            additional-maven-args: "-Pjacoco,coveralls -X"
          - java: 21

    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: | 
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-
      - name: Build with Maven and SonarCloud
        run: > 
          xvfb-run mvn clean verify ${{ matrix.additional-maven-args }}
          -Dcoveralls.repoToken=${{ secrets.COVERALLS_TOKEN }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLOUD }}
          POSTGRES_TEST_DB: ${{ secrets.POSTGRES_TEST_DB }}
          POSTGRES_TEST_USER: ${{ secrets.POSTGRES_TEST_USER }}
          POSTGRES_TEST_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}

      - name: Archive Surefire XML reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-xml-jdk-${{ matrix.java }}
          path: '**/target/surefire-reports/'