name: Java CI Build with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 17
            additional-maven-args: "-Pjacoco,mutation-testing,html-report " # add coveralls:report then
          - java: 21

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}

      - name: Build with Maven
        run: mvn clean verify ${{ matrix.additional-maven-args }}
        working-directory: ./sessionBuilderParent
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_TOKEN }}
		  
		# temporary
	  - name: Upload to Coveralls (non-blocking)
  		run: mvn coveralls:report || echo "Coveralls failed but build continues"

      - name: Archive Surefire XML reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-xml-jdk-${{ matrix.java }}
          path: '**/target/surefire-reports/'

#      - name: Archive Surefire HTML report
#        uses: actions/upload-artifact@v4
#        if: ${{ always() }}
#        with:
#          name: surefire-html-jdk-${{ matrix.java }}
#          path: '**/target/site/surefire-report.html'
