name: Java CI Build with Maven

on:
  push:
  pull_request:

jobs:
  build:
    env:
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLOUD }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - java: 17
            additional-maven-args: "-Pjacoco,mutation-testing,app-docker,coveralls"
          - java: 21
            additional-maven-args: ""

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Set up JDK ${{ matrix.java }}
        uses: actions/setup-java@v4
        with:
          java-version: ${{ matrix.java }}
          distribution: 'temurin'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.m2
            ~/.sonar/cache
          key: ${{ runner.os }}-m2-jdk-${{ matrix.java }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2-

      - name: Build with Maven
        run: >
          xvfb-run mvn -B clean install ${{ matrix.additional-maven-args }}
          -Dcoveralls.repoToken=${{ secrets.COVERALLS_TOKEN }}
        env:
          POSTGRES_DB: ${{ secrets.POSTGRES_TEST_DB }}
          POSTGRES_USER: ${{ secrets.POSTGRES_TEST_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_TEST_PASSWORD }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CI_NAME: github
          CI_BUILD_NUMBER: ${{ github.run_number }}
          CI_BRANCH: ${{ github.ref_name }}

      - name: Analyze with SonarCloud
        if: success() && matrix.java == '17'
        run: mvn sonar:sonar -Psonarcloud
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN_CLOUD }}

      - name: Create Temporary Junit Reports
        run: mvn surefire-report:report-only
        if: ${{ always() }}

      - name: Archive Junit Reports
        uses: actions/upload-artifact@v4
        if: ${{ always() }}
        with:
          name: surefire-report-jdk-${{ matrix.java }}
          path: '**/target/reports'

      - name: Archive Jacoco-Aggregate Report
        uses: actions/upload-artifact@v4
        if: ${{ always() && matrix.java == '17' }}
        with:
          name: jacoco-aggregate-report
          path: ./sessionBuilder/sessionBuilder-report/target/site/jacoco-aggregate

      - name: Archive Pit Report
        uses: actions/upload-artifact@v4
        if: ${{ always() && matrix.java == '17' }}
        with:
          name: pit-report
          path: ./sessionBuilder/sessionBuilder-core/target/pit-reports

      - name: Login to DockerHub
        if: matrix.java == '17' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to DockerHub
        if: matrix.java == '17' && github.ref == 'refs/heads/main'
        run: |
          docker tag sessionbuilder-app:0.0.1-SNAPSHOT ${{ secrets.DOCKERHUB_USERNAME }}/sessionbuilder-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/sessionbuilder-app:latest
        working-directory: ./sessionBuilder-app